apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: music
  name: music-alb-haproxymusic-ingress
  annotations:
     kubernetes.io/ingress.class: "music"
spec:
  rules:
  - host : warmpillow.xyz
    http:
      paths:
      #- path: /*
      - backend:
         serviceName: ampache-service
         servicePort: 8054
  - host : warmpillow.xyz
    http:
      paths:
      - path: /ws
        backend:
         serviceName: ampache-service
         servicePort: 8100
  tls:
   - secretName: nirvana-ssl
     hosts:
      - warmpillow.xyz
