apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: nirvana-ingress
  namespace: music
  annotations:
     #kubernetes.io/tls-acme: "true"
     kubernetes.io/ingress.allow-http: "false"
spec:
  backend:
    serviceName: ampache-service
    servicePort: 8054
  tls:
   - secretName: nirvana-ssl
     hosts:
      - warmpillow.xyz
